CREATE TABLE ELEMENTOR.ANALYTICS.COUNTRIES ( 
	COUNTRY_ISO2         varchar(2) NOT NULL  ,
	COUNTRY_NAME         varchar(16777216)   ,
	CONSTRAINT PK_COUNTRIES_COUNTRY_ISO2 PRIMARY KEY ( COUNTRY_ISO2 )
 );

CREATE TABLE ELEMENTOR.ANALYTICS.CUSTOMERS ( 
	CUSTOMER_ID          number(38,0) NOT NULL  ,
	CREATED_TS           timestampntz   ,
	RECORD_OPEN_TS       timestampntz   ,
	RECORD_CLOSE_TS      timestampntz   ,
	"NAME"               varchar(16777216)   ,
	VAT_ID               varchar(16777216)   ,
	COMPANY              varchar(16777216)   ,
	COUNTRY_ISO2         varchar(2)   ,
	COUNTRY_STATE        varchar(16777216)   ,
	EMAIL_ADDRESS        varchar(16777216)   ,
	" RECORD_OPEN_TS"    varchar   ,
	CONSTRAINT PK_CUSTOMERS_CUSTOMER_ID PRIMARY KEY ( CUSTOMER_ID ),
	CONSTRAINT FK_CUSTOMERS_COUNTRIES FOREIGN KEY ( COUNTRY_ISO2 ) REFERENCES ELEMENTOR.ANALYTICS.COUNTRIES( COUNTRY_ISO2 ) ON DELETE NO ACTION ON UPDATE NO ACTION
 )  CLUSTER BY (CUSTOMER_ID);

CREATE TABLE ELEMENTOR.ANALYTICS.DIM_DATE ( 
	DATE                 date NOT NULL  ,
	DAY                  number(38,0)   ,
	MONTH                number(38,0)   ,
	YEAR                 number(38,0)   ,
	QUARTER              number(38,0)   ,
	QUARTER_YEAR         varchar(10)   ,
	MONTH_NAME           varchar(3)   ,
	FISCAL_YEAR          varchar(10)   ,
	FLAG_IS_LAST_7_DAYS  number(38,0)   ,
	FLAG_IS_LAST_14_DAYS number(38,0)   ,
	CONSTRAINT PK_DIM_DATE_DATE PRIMARY KEY ( DATE )
 );

CREATE TABLE ELEMENTOR.ANALYTICS.MEDIA ( 
	DATE                 date   ,
	MEDIA_SPENT          double(0,0)   ,
	MEDIA_REVENUE        double(0,0)   ,
	CONSTRAINT FK_MEDIA_DIM_DATE FOREIGN KEY ( DATE ) REFERENCES ELEMENTOR.ANALYTICS.DIM_DATE( DATE ) ON DELETE NO ACTION ON UPDATE NO ACTION
 );

CREATE TABLE ELEMENTOR.ANALYTICS.PLANS ( 
	PLAN_ID              number(38,0)   ,
	PLAN_NAME            varchar(16777216)   ,
	PLAN_PRICE           double(0,0)   ,
	CURRENCY             varchar(3)   ,
	PLAN_OPEN_DATE       date   ,
	PLAN_CLOSE_DATE      date   ,
	" PLAN_OPEN_DATE"    varchar   
 )  CLUSTER BY (PLAN_ID);

CREATE TABLE ELEMENTOR.ANALYTICS.PURCHASES ( 
	CREATED_DATE         date   ,
	UPDATE_DATE          date   ,
	USER_ID              number(38,0)   ,
	CUSTOMER_ID          number(38,0)   ,
	PAYMENT_ID           number(38,0)   ,
	REFUND_ID            number(38,0)   ,
	REFUND_DATE          date   ,
	TRANSACTION_LAST_STATUS varchar(10)   ,
	PLAN_ID              number(38,0)   ,
	LICENSE_ID           number(38,0)   ,
	AFFILIATE_ID         number(38,0)   ,
	AFFILIATE_FEE        double(0,0)   ,
	DISCOUNT_ID          varchar(16777216)   ,
	NET_TOTAL            double(0,0)   ,
	TAX                  double(0,0)   ,
	TOTAL_WITH_TAX       double(0,0)   ,
	NET_REFUND           double(0,0)   ,
	TAX_REFUND           double(0,0)   ,
	TOTAL_REFUND         double(0,0)   ,
	NET_PARTIAL_REFUND   double(0,0)   ,
	TAX_PARTIAL_REFUND   double(0,0)   ,
	TOTAL_PARTIAL_REFUND double(0,0)   ,
	PARTIAL_REFUND_DATE  date   ,
	NET_NEW              double(0,0)   ,
	NEW_RENEW            double(0,0)   ,
	NET_UPGRADE          double(0,0)   ,
	NET_DOWNGRADE        double(0,0)   ,
	ACTION_NEW           number(38,0)  DEFAULT 0 ,
	ACTION_REFUND        number(38,0)  DEFAULT 0 ,
	ACTION_RENEW         number(38,0)  DEFAULT 0 ,
	ACTION_UPGRADE       number(38,0)  DEFAULT 0 ,
	ACTION_DOWNGRADE     number(38,0)  DEFAULT 0 ,
	ACTION_FAILED        number(38,0)  DEFAULT 0 ,
	ACTION_REVOKED       number(38,0)  DEFAULT 0 ,
	ACTION_ABANDONED     number(38,0)  DEFAULT 0 ,
	PAYMENT_GATEWAY      varchar(16777216)   ,
	CONSTRAINT FK_PURCHASES_CUSTOMERS FOREIGN KEY ( CUSTOMER_ID ) REFERENCES ELEMENTOR.ANALYTICS.CUSTOMERS( CUSTOMER_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_PURCHASES_DIM_DATE FOREIGN KEY ( CREATED_DATE ) REFERENCES ELEMENTOR.ANALYTICS.DIM_DATE( DATE ) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_PURCHASES_PLANS FOREIGN KEY ( PLAN_ID ) REFERENCES ELEMENTOR.ANALYTICS.PLANS( PLAN_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION
 );

CREATE TABLE ELEMENTOR.ANALYTICS.TOP_SITES ( 
	DOMAIN               varchar(16777216) NOT NULL  ,
	RANK                 number(38,0)   ,
	OPEN_PAGE_RANK       double(0,0)   ,
	_INDEX_2             varchar(16777216)   ,
	CONSTRAINT PK_TOP_SITES_DOMAIN PRIMARY KEY ( DOMAIN )
 );

CREATE TABLE ELEMENTOR.ANALYTICS.LICNESE ( 
	LICENSE_ID           number(38,0) NOT NULL  ,
	PLAN_ID              number(38,0)   ,
	START_TS             timestampntz   ,
	EXPIRATION_TS        timestampntz   ,
	CONSTRAINT PK_LICNESE_LICENSE_ID PRIMARY KEY ( LICENSE_ID ),
	CONSTRAINT FK_LICNESE_PURCHASES FOREIGN KEY ( LICENSE_ID ) REFERENCES ELEMENTOR.ANALYTICS.PURCHASES( LICENSE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION
 );

CREATE TABLE ELEMENTOR.ANALYTICS.LICENSE_DOMAINS ( 
	LICENSE_ID           number(38,0)   ,
	DOMAIN               varchar(16777216)   ,
	CONSTRAINT FK_LICENSE_DOMAINS_LICNESE FOREIGN KEY ( LICENSE_ID ) REFERENCES ELEMENTOR.ANALYTICS.LICNESE( LICENSE_ID ) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT FK_LICENSE_DOMAINS_TOP_SITES FOREIGN KEY ( DOMAIN ) REFERENCES ELEMENTOR.ANALYTICS.TOP_SITES( DOMAIN ) ON DELETE NO ACTION ON UPDATE NO ACTION
 );

